version: "3.9"

services:
    jenkins:
        image: jenkins/jenkins:jdk11
        container_name: jenkinscompose
        ports:
        - "8880:8080"
        - "5000:50000"
        volumes: 
        - ../volumes/jenkins/:/var/jenkins_home
        networks: 
        - "docker_network"

    ubuntu_slave:
        depends_on: 
            - jenkins
        container_name: ubuntucompose
        volumes: 
            - /var/run/docker.sock:/var/run/docker.sock
        build:
            context: ../dockerfiles/slave/
        command: java -jar agent.jar -jnlpUrl http://jenkins:8080/computer/slave/jenkins-agent.jnlp -secret 8c7e39d9d48e2ebe13f75b94a3ef26ee58fc4e717cdb5729eba25aecf3659ff1 -workDir "/home/"
        networks: 
        - "docker_network"

    selenium_hub:
        image: selenium/hub
        container_name: selenium-hubcompose
        ports: 
        - "4444:4444"
        networks: 
        - docker_network

    firefox:
        image: selenium/node-firefox
        container_name: firefoxcompose
        depends_on: 
        - selenium_hub
        environment: 
        - HUB_HOST=seleniumhub
        - HUB_PORT=4444
        networks: 
        - docker_network

    artifactory:
        image: docker.bintray.io/jfrog/artifactory-oss:latest
        container_name: artifatorycompose
        volumes:
        - ../volumes/artifactory:/var/opt/jfrog/artifactory
        ports:
        - "8081:8081"
        - "8082:8082"
        networks:
        - docker_network

networks:
    docker_network:
        driver: bridge